replicaCount: 2

image:
  repository: 533267139926.dkr.ecr.us-east-1.amazonaws.com/eks-gitops-flask
  tag: "v1.0.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

health:
  path: /health